---
title: "Final Project Milestone 3"
author: "Michael Wu"
date: "2/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(reprex)
library(janitor)
library(gt)
library(readr)
library(rvest)
```

```{r loading_data, echo=FALSE, results='hide'}
untidy_covidata <- read_csv('JH-covid19-rawdata/time_series_19-covid-Confirmed.csv', col_types = cols(
                              .default = col_double(),
                              `Province/State` = col_character(),
                              `Country/Region` = col_character()
                              )
                            ) %>%
  clean_names()
```

```{r tidying-data, echo=FALSE, results='hide'}
covidata <- untidy_covidata %>%
  pivot_longer(
    cols = starts_with("x"),
    names_to = "date",
    names_prefix = "x",
    values_to = "cases",
    values_drop_na = TRUE
  )
```

$~$

```{r display-untidy-table, echo=FALSE}
untidy_covidata %>%
  slice(1:5) %>%
  select(province_state, country_region, lat, long, x1_22_20, x1_23_20, x1_24_20, x1_25_20, x2_27_20) %>%
  gt() %>% 
  tab_header(
    title = "Glimpse of Untidy Covid-19 Data"
  ) %>%
  cols_label(
    province_state = "Province/State",
    country_region = "Country",
    lat = "Latitude",
    long = "Longitude"
  ) %>%
  cols_align(
    align = "center"
  ) %>%
  tab_footnote(
    footnote = "Source: Johns Hopkins University, Ryan Lau on Github",
    locations = cells_title(
      groups = "title"
    )
  ) %>%
  tab_footnote(
    footnote = "First five rows displayed only",
    locations = cells_title(
      groups = "title"
    )
  )
```

$~$

```{r display-tidy-table, echo=FALSE}
covidata %>%
  slice(1:5)%>%
  gt() %>% 
  tab_header(
    title = "Glimpse of Tidied Covid-19 Data"
  ) %>%
  cols_label(
    province_state = "Province/State",
    country_region = "Country",
    lat = "Latitude",
    long = "Longitude",
    date = "Date",
    cases = "Number of Cases"
  ) %>%
  cols_align(
    align = "center"
  ) %>%
  tab_footnote(
    footnote = "Source: Johns Hopkins University, Ryan Lau on Github",
    locations = cells_title(
      groups = "title"
    )
  ) %>%
  tab_footnote(
    footnote = "First five rows displayed only",
    locations = cells_title(
      groups = "title"
    )
  )
  
```