---
title: "Final Project Milestone 6"
author: "Michael Wu"
date: "4/03/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(reprex)
library(janitor)
library(gt)
library(readr)
library(readxl)
library(rvest)
library(ggthemes)
```

### the Coronavirus Project.

### New Updates for the Sixth Milestone


```{r loading_data, echo=FALSE, results='hide'}
# Loading the untidy version of the coronavirus data forked from the Johns Hopkins' GitHub repo
# Specifying column types to avoid any forms of errors

untidy_covidata_global <- read_csv('JH-covid19-rawdata/time_series_covid19_confirmed_global.csv', col_types = cols(
                              .default = col_double(),
                              `Province/State` = col_character(),
                              `Country/Region` = col_character()
                              )
                            ) %>%
  clean_names()

untidy_covidata_us <- read_csv('JH-covid19-rawdata/time_series_covid19_confirmed_US.csv', col_types = cols(
                                .default = col_double(),
                                iso2 = col_character(),
                                iso3 = col_character(),
                                Admin2 = col_character(),
                                Province_State = col_character(),
                                Country_Region = col_character(),
                                Combined_Key = col_character()
                              )
                            ) %>%
  clean_names()

```

```{r tidying-data, echo=FALSE, results='hide'}
# Tidying the untidy_covidata tibble using pivot_longer
# Pivoting so that dates will now be row data entries instead of columns as they were originally
# Removing extraneous or unecessary columns so that the tibble will be smaller, these are huge data tables

covidata_global <- untidy_covidata_global %>%
  pivot_longer(
    cols = starts_with("x"),
    names_to = "date",
    names_prefix = "x",
    values_to = "cases",
    values_drop_na = TRUE
  ) %>%
  select(-lat, -long)

covidata_us <- untidy_covidata_us %>%
  pivot_longer(
    cols = starts_with("x"),
    names_to = "date",
    names_prefix = "x",
    values_to = "cases",
    values_drop_na = TRUE
  ) %>%
  select(-uid, -iso2, -iso3, -code3, -fips, -lat, -long, -combined_key) %>%
  rename(county = admin2, country = country_region)
```


```{r plot-italy-covidata, echo = FALSE}
italy_covidata <- covidata_global %>%
  filter(country_region == "Italy")

italy_plot <- ggplot(italy_covidata, aes(x = as.Date(date,"%m_%d_%y"), y = cases)) +
  geom_line() +
  labs(title = "Italy Covid-19 Cases",
       subtitle = "As of March 20th, 2020",
       x = "Case Count",
       y = "Date") +
  theme_classic()
  
```

### Preliminary Plots for the Coronavirus Outbreak

$~$

```{r plot-country-covidata, fig.align='center', echo = FALSE}
filtered_covidata <- covidata_global %>%
  filter(country_region %in% c("Italy", "Korea, South", "Spain", "France", "Germany", "Iran")) %>%
  filter(is.na(province_state) | province_state == "France")

ggplot(filtered_covidata, aes(x = as.Date(date,"%m_%d_%y"), y = cases, color = country_region)) +
  geom_line() +
  labs(title = "Confirmed Covid-19 Cases of the Most Affected Countries",
       subtitle = "As of March 20th, Excluding China and the United States",
       x = "Date",
       y = "Case Count") +
  theme_classic()
  
```

```{r plot-US-covidata, fig.align='center', echo = FALSE}
# Find the most affected states in the United States
# Would use log scales like in China's case below, but the case reporting is so erratic
# that the graphs for log scales on the y-axis looks so poor.
# NEED TO: do some basic data cleanup because the graph displays all the county-wide 
# confirmed case counts instead of the totals for the state

US_covidata <- covidata_us %>%
  filter(province_state %in% c("New York", "Washington", "California", "New Jersey"))

ggplot(US_covidata, aes(x = as.Date(date,"%m_%d_%y"), y = cases, color = province_state)) +
  geom_line() +
  labs(title = "Confirmed Covid-19 Cases in China's 4 Most Affected Provinces",
       subtitle = "As of March 20th, In Log Scale",
       x = "Date",
       y = "Case Count") +
  theme_classic()
  
```

$~$
